
import type { Metadata } from "next";
import {Geist, Geist_Mono, Space_Grotesk} from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import {CreateWorkspaceModal} from "@/features/workspaces/components/create-workspace-modal";
import {Modals} from "@/components/modals";
import {Toaster} from "@/components/ui/sonner";
import JotaiProvider from "@/components/jotai-provider";
import {NuqsAdapter} from "nuqs/adapters/react";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {ReactQueryProvider} from "@/components/ReactQueryProvider";

export const calsans = Space_Grotesk({
    subsets: ["latin"],
    variable: "--font-calsans",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wack",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ConvexAuthNextjsServerProvider>
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConvexClientProvider>
            <JotaiProvider>
                <ReactQueryProvider >
                    <NuqsAdapter>
                        <Toaster/>
                        <Modals/>
                        {children}
                    </NuqsAdapter>
                </ReactQueryProvider>
            </JotaiProvider>
        </ConvexClientProvider>
        </body>
        </html>
      </ConvexAuthNextjsServerProvider>
  );
}
